import { Montserrat } from "next/font/google";
import "./globals.css";
import ThemeProviderClient from "@/components/ThemeProviderClient";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],   // pick whichever weights you need
});

export const metadata = {
  title: "RENATA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        <ThemeProviderClient>
          {children}
        </ThemeProviderClient>
      </body>
    </html>
  );
}
